secretGenerator:
  - name: trading-app
    literals:
      - user=postgres
      - password=password
      - FINNHUB_TOKEN=d5ipqopr01qicq2k4vhgd5ipqopr01qicq2k4vi0
resources:
  - psql-deployment.yaml
  - trading-deployment.yaml
